/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImageAnalysisRouteImport } from './routes/image-analysis'
import { Route as MissionAnalysisRouteImport } from './routes/mission-analysis'
import { Route as MissionMapRouteImport } from './routes/mission-map'
import { Route as ReportsRouteImport } from './routes/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageAnalysisRoute = ImageAnalysisRouteImport.update({
  id: '/image-analysis',
  path: '/image-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionAnalysisRoute = MissionAnalysisRouteImport.update({
  id: '/mission-analysis',
  path: '/mission-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionMapRoute = MissionMapRouteImport.update({
  id: '/mission-map',
  path: '/mission-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/mission-analysis': typeof MissionAnalysisRoute
  '/mission-map': typeof MissionMapRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/mission-analysis': typeof MissionAnalysisRoute
  '/mission-map': typeof MissionMapRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/mission-analysis': typeof MissionAnalysisRoute
  '/mission-map': typeof MissionMapRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/image-analysis' | '/mission-analysis' | '/mission-map' | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/image-analysis' | '/mission-analysis' | '/mission-map' | '/reports'
  id:
    | '__root__'
    | '/'
    | '/image-analysis'
    | '/mission-analysis'
    | '/mission-map'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageAnalysisRoute: typeof ImageAnalysisRoute
  MissionAnalysisRoute: typeof MissionAnalysisRoute
  MissionMapRoute: typeof MissionMapRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-analysis': {
      id: '/image-analysis'
      path: '/image-analysis'
      fullPath: '/image-analysis'
      preLoaderRoute: typeof ImageAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-analysis': {
      id: '/mission-analysis'
      path: '/mission-analysis'
      fullPath: '/mission-analysis'
      preLoaderRoute: typeof MissionAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-map': {
      id: '/mission-map'
      path: '/mission-map'
      fullPath: '/mission-map'
      preLoaderRoute: typeof MissionMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageAnalysisRoute: ImageAnalysisRoute,
  MissionAnalysisRoute: MissionAnalysisRoute,
  MissionMapRoute: MissionMapRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
